# Import TypedDict for defining the state structure
from typing import TypedDict

# State structure used throughout the LangGraph workflow
class CustomerSupportState(TypedDict):

    # Customer name
    customer_name: str

    # Customer query
    query: str

    # Classified intent
    intent: str

    # Assigned department
    department: str

    # Context retrieved from RAG
    retrieved_context: str

    # Context retrieved from memory
    memory_context: str

    # Indicates whether approval is required
    approval_required: bool

    # Stores supervisor approval status
    approval_status: str

    # Response generated by support agent
    agent_response: str

    # Final response sent to customer
    final_response: str